// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.disid.proofs.repository;

import com.disid.proofs.domain.Agent;
import com.disid.proofs.repository.AgentRepository;
import com.disid.proofs.repository.AgentRepositoryCustom;
import io.springlets.data.jpa.repository.DetachableJpaRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AgentRepository_Roo_Jpa_Repository {
    
    declare parents: AgentRepository extends DetachableJpaRepository<Agent, Long>;
    
    declare parents: AgentRepository extends AgentRepositoryCustom;
    
    declare @type: AgentRepository: @Transactional(readOnly = true);
    
}
