// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.disid.proofs.repository;

import com.disid.proofs.domain.Agent;
import com.disid.proofs.domain.QAgent;
import com.disid.proofs.repository.AgentRepositoryCustom;
import com.disid.proofs.repository.AgentRepositoryImpl;
import com.querydsl.core.types.Path;
import com.querydsl.jpa.JPQLQuery;
import io.springlets.data.domain.GlobalSearch;
import io.springlets.data.jpa.repository.support.QueryDslRepositorySupportExt.AttributeMappingBuilder;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AgentRepositoryImpl_Roo_Jpa_Repository_Impl {
    
    declare parents: AgentRepositoryImpl implements AgentRepositoryCustom;
    
    declare @type: AgentRepositoryImpl: @Transactional(readOnly = true);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String AgentRepositoryImpl.NAME = "name";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String AgentRepositoryImpl.COMPANY = "company";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public Page<Agent> AgentRepositoryImpl.findAll(GlobalSearch globalSearch, Pageable pageable) {
        
        QAgent agent = QAgent.agent;
        
        JPQLQuery<Agent> query = from(agent);
        
        Path<?>[] paths = new Path<?>[] {agent.name,agent.company};        
        applyGlobalSearch(globalSearch, query, paths);
        
        AttributeMappingBuilder mapping = buildMapper()
			.map(NAME, agent.name)
			.map(COMPANY, agent.company);
        
        applyPagination(pageable, query, mapping);
        applyOrderById(query);
        
        return loadPage(query, pageable, agent);
    }
    
}
