// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.disid.proofs.web;

import com.disid.proofs.domain.Agent;
import com.disid.proofs.service.api.AgentService;
import com.disid.proofs.web.AgentDeserializer;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import io.springlets.web.NotFoundException;
import java.io.IOException;
import org.springframework.boot.jackson.JsonComponent;
import org.springframework.core.convert.ConversionService;

privileged aspect AgentDeserializer_Roo_EntityDeserializer {
    
    declare @type: AgentDeserializer: @JsonComponent;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return AgentService
     */
    public AgentService AgentDeserializer.getAgentService() {
        return agentService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param agentService
     */
    public void AgentDeserializer.setAgentService(AgentService agentService) {
        this.agentService = agentService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ConversionService
     */
    public ConversionService AgentDeserializer.getConversionService() {
        return conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param conversionService
     */
    public void AgentDeserializer.setConversionService(ConversionService conversionService) {
        this.conversionService = conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param jsonParser
     * @param context
     * @param codec
     * @param tree
     * @return Agent
     * @throws IOException
     */
    public Agent AgentDeserializer.deserializeObject(JsonParser jsonParser, DeserializationContext context, ObjectCodec codec, JsonNode tree) throws IOException {
        String idText = tree.asText();
        Long id = conversionService.convert(idText, Long.class);
        Agent agent = agentService.findOne(id);
        if (agent == null) {
            throw new NotFoundException("Agent not found");
        }
        return agent;
    }
    
}
