// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.disid.proofs.web;

import com.disid.proofs.service.api.AgentService;
import com.disid.proofs.web.AgentsItemThymeleafController;

privileged aspect AgentsItemThymeleafController_Roo_Controller {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private AgentService AgentsItemThymeleafController.agentService;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return AgentService
     */
    public AgentService AgentsItemThymeleafController.getAgentService() {
        return agentService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param agentService
     */
    public void AgentsItemThymeleafController.setAgentService(AgentService agentService) {
        this.agentService = agentService;
    }
    
}
