// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.disid.proofs.service.api;

import com.disid.proofs.domain.Agent;
import com.disid.proofs.service.api.AgentService;
import io.springlets.data.domain.GlobalSearch;
import io.springlets.format.EntityResolver;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

privileged aspect AgentService_Roo_Service {
    
    declare parents: AgentService extends EntityResolver<Agent, Long>;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return Agent
     */
    public abstract Agent AgentService.findOne(Long id);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param agent
     */
    public abstract void AgentService.delete(Agent agent);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entities
     * @return List
     */
    public abstract List<Agent> AgentService.save(Iterable<Agent> entities);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     */
    public abstract void AgentService.delete(Iterable<Long> ids);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entity
     * @return Agent
     */
    public abstract Agent AgentService.save(Agent entity);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return Agent
     */
    public abstract Agent AgentService.findOneForUpdate(Long id);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @return List
     */
    public abstract List<Agent> AgentService.findAll(Iterable<Long> ids);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return List
     */
    public abstract List<Agent> AgentService.findAll();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    public abstract long AgentService.count();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public abstract Page<Agent> AgentService.findAll(GlobalSearch globalSearch, Pageable pageable);
    
}
