// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.clinictests.web;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.springframework.roo.clinictests.domain.Pet;
import org.springframework.roo.clinictests.domain.Vet;
import org.springframework.roo.clinictests.web.PetDeserializer;
import org.springframework.roo.clinictests.web.VetDeserializer;
import org.springframework.roo.clinictests.web.VisitJsonMixin;

privileged aspect VisitJsonMixin_Roo_JSONMixin {
    
    /**
     * TODO Auto-generated attribute documentation
     */
    @JsonDeserialize(using = PetDeserializer.class)
    private Pet VisitJsonMixin.pet;
    
    /**
     * TODO Auto-generated attribute documentation
     */
    @JsonDeserialize(using = VetDeserializer.class)
    private Vet VisitJsonMixin.vet;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Pet
     */
    public Pet VisitJsonMixin.getPet() {
        return pet;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param pet
     */
    public void VisitJsonMixin.setPet(Pet pet) {
        this.pet = pet;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Vet
     */
    public Vet VisitJsonMixin.getVet() {
        return vet;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param vet
     */
    public void VisitJsonMixin.setVet(Vet vet) {
        this.vet = vet;
    }
    
}
