// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.petclinic.domain;

import javax.persistence.Entity;
import org.springframework.roo.petclinic.domain.Visit;

privileged aspect Visit_Roo_Jpa_Entity {
    
    declare @type: Visit: @Entity;
    
}
