// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.disid.proofs.domain;

import com.disid.proofs.domain.Agent;

privileged aspect Agent_Roo_JavaBean {
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return String
     */
    public String Agent.getCompany() {
        return this.company;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param company
     */
    public void Agent.setCompany(String company) {
        this.company = company;
    }
    
}
