// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.clinictests.dod;

import org.springframework.roo.clinictests.domain.Visit;

import java.util.Calendar;
import java.util.Date;

public class VisitFactory {

  public Visit create(int index) {
    Visit obj = new Visit();
    setCreatedBy(obj, index);
    setCreatedDate(obj, index);
    setDescription(obj, index);
    setModifiedBy(obj, index);
    setModifiedDate(obj, index);
    setVisitDate(obj, index);
    return obj;
  }

  private void setCreatedBy(Visit obj, int index) {
    String createdBy = "createdBy_" + index;
    obj.setCreatedBy(createdBy);
  }

  private void setCreatedDate(Visit obj, int index) {
    Calendar createdDate = Calendar.getInstance();
    obj.setCreatedDate(createdDate);
  }

  private void setDescription(Visit obj, int index) {
    String description = "description_" + index;
    if (description.length() > 255) {
      description = description.substring(0, 255);
    }
    obj.setDescription(description);
  }

  private void setModifiedBy(Visit obj, int index) {
    String modifiedBy = "modifiedBy_" + index;
    obj.setModifiedBy(modifiedBy);
  }

  private void setModifiedDate(Visit obj, int index) {
    Calendar modifiedDate = Calendar.getInstance();
    obj.setModifiedDate(modifiedDate);
  }

  private void setVisitDate(Visit obj, int index) {
    Date visitDate = new Date(new Date().getTime() - 10000000L);
    obj.setVisitDate(visitDate);
  }

}
