// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.clinictests.domain;

import io.springlets.format.EntityFormat;
import org.springframework.roo.clinictests.domain.PetNameAndWeightFormBean;

privileged aspect PetNameAndWeightFormBean_Roo_DTO {
    
    declare @type: PetNameAndWeightFormBean: @EntityFormat;
    
}
